language: java
jdk:
  - oraclejdk8
sudo: false

services:
  - docker

cache:
  directories:
  - $HOME/.m2

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn install -DskipTests -Pdefault,docker
  - mvn deploy -DskipTests -Pdocker
  - docker tag marketreaction/predictor:$TRAVIS_BUILD_NUMBER marketreaction/predictor:latest
  - docker push marketreaction/predictor:latest